### ISSUE TITLE
3D images

### ISSUE THREAD

**Issue by luciantunez** [NVlabs/flip#1]
Hello and thank you for sharing your work! 
Do you thing it would be possible to apply your algorithm to a 3D image? Les's say an MRI for example. 
Would you recommend any other tool for this if it weren't possible?
Thank you in advance!

**Comment by inversepixel** [comment]
Hello there!
From my perspective, I think it would make sense to apply FLIP to all XY, all YZ, and all XZ slices of your 3D image.
I believe that makes most sense, since you cannot know which data in your 3D image that will be visible after you apply your transfer function. Hopefully you can easily make a python script that does this for you.
Let us know how it goes!
Thanks!
/Tomas
